version: '3.9'

services:
  monolithic-web:
    container_name: monolithic-web
    image: monolithic-web:latest
    build: .
    hostname: monolithic-web
    env_file: 
      - .env
    ports:
      - 8008:80     # frontend
    depends_on:
      monolithic-db:
        condition: service_healthy
      monolithic-adminer:
        condition: service_started
    volumes:
      - .:/var/www/html/
      - ./php.ini:/usr/local/etc/php/php.ini

  monolithic-db:
    container_name: monolithic-db
    image: postgres:16
    hostname: monolithic-db
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ${MONOLITHIC_POSTGRES_USER}i
      POSTGRES_PASSWORD: ${MONOLITHIC_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MONOLITHIC_POSTGRES_DB}
      POSTGRES_DATA: ${MONOLITHIC_POSTGRES_DATA}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MONOLITHIC_POSTGRES_USER} -d ${MONOLITHIC_POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db:/var/lib/postgresql/data/

  monolithic-adminer:
    container_name: monolithic-adminer
    image: adminer:4.8.1
    hostname: monolithic-adminer
    depends_on:
      - monolithic-db
    ports:
      - 8080:8080