version: '3.3'
services:
  web:
    image: php:8.0-apache
    ports:
      - 8008:80

  postgresql:
    image: postgres:latest
    ports:
      - 5555:5432

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
