version: '3.3'
services:
  tubes-web:
    container_name: tubes-web
    image: tubes-1:latest
    hostname: tubes-web
    env_file: 
      - .env
    networks:
      - tubes
    ports:
      - 8008:80
    depends_on:
      tubes-db:
        condition: service_healthy
      tubes-adminer:
        condition: service_started
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./index.php:/var/www/html/index.php
      - ./routes.php:/var/www/html/routes.php
      - ./phpinfo.php:/var/www/html/phpinfo.php
      - ./.env:/var/www/html/.env
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini

  tubes-db:
    container_name: tubes-db
    image: postgres:latest
    hostname: tubes-db
    networks:
      - tubes
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DATA: ${POSTGRES_DATA}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db:/var/lib/postgresql/data/

  tubes-adminer:
    container_name: tubes-adminer
    image: adminer:latest
    hostname: tubes-adminer
    networks:
      - tubes
    depends_on:
      - tubes-db
    ports:
      - 8080:8080

networks:
  tubes:
