version: '3.3'
services:
  tubes-web:
    container_name: tubes-web
    image: tubes-1:latest
    hostname: tubes-web
    env_file: 
      - .env
    networks:
      - tubes
    ports:
      - 8008:80
    depends_on:
      tubes-db:
        condition: service_healthy
      tubes-adminer:
        condition: service_started
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src

  tubes-db:
    container_name: tubes-db
    image: postgres:latest
    hostname: tubes-db
    networks:
      - tubes
    ports:
      - 5433:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: 
      - .env
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

  tubes-adminer:
    container_name: tubes-adminer
    image: adminer:latest
    hostname: tubes-adminer
    networks:
      - tubes
    depends_on:
      - tubes-db
    ports:
      - 8080:8080

networks:
  tubes:
